//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitConduitTable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logs_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitConduitTable.Resources.Logs_Text", typeof(Logs_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during startup.
        /// </summary>
        internal static string APP_STARTUP_ERROR {
            get {
                return ResourceManager.GetString("APP_STARTUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting RevitConduitTableApp.
        /// </summary>
        internal static string APP_STARTUP_INFO {
            get {
                return ResourceManager.GetString("APP_STARTUP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing ConduitButton CMD error.
        /// </summary>
        internal static string BUTTON_CONDUIT_ERROR {
            get {
                return ResourceManager.GetString("BUTTON_CONDUIT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing ConduitButton CMD.
        /// </summary>
        internal static string BUTTON_CONDUIT_INFO {
            get {
                return ResourceManager.GetString("BUTTON_CONDUIT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting table Error.
        /// </summary>
        internal static string EXPORT_EXCEL_ERORR {
            get {
                return ResourceManager.GetString("EXPORT_EXCEL_ERORR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource key {0} not found for culture {1}.
        /// </summary>
        internal static string LOCALIZATION_KEY_WARN {
            get {
                return ResourceManager.GetString("LOCALIZATION_KEY_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load resource for culture {0}.
        /// </summary>
        internal static string LOCALIZATION_LOAD_ERROR {
            get {
                return ResourceManager.GetString("LOCALIZATION_LOAD_ERROR", resourceCulture);
            }
        }
    }
}
